version: "3.9"

services:
  web:
    build: .
    #command: python /code/manage.py runserver 0.0.0.0:8000 
    command: gunicorn social.wsgi -b 0.0.0.0:8000
    restart: always 
    volumes:
      - .:/code 
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    restart: always 
    volumes:
      - ./data/db:/var/lib/sqlite3/data
    environment:
      - SQLITE3_DB=db.sqlite3

