# Generated by Django 4.1 on 2023-01-21 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_alter_profile_follows_delete_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="follower",
            field=models.ManyToManyField(
                blank=True, related_name="follower", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
