# Generated by Django 4.1 on 2023-01-21 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0006_profile_follower"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="follower",
        ),
        migrations.AlterField(
            model_name="profile",
            name="follows",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="follows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
