# Generated by Django 4.1 on 2023-01-21 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0007_remove_profile_follower_alter_profile_follows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="follows", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
