# Generated by Django 4.1 on 2023-01-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True, default="This is my bio.", max_length=200, null=True
            ),
        ),
    ]
